apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nrdot.fullname" . }}-{{ .name }}
  labels:
    {{- include "nrdot.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nrdot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nrdot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nrdot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .metricsPort }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .config.configMap }}
          volumeMounts:
            - name: config
              mountPath: /config
          {{- end }}
          # Add health and readiness probes
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .metricsPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .metricsPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
      {{- if .config.configMap }}
      volumes:
        - name: config
          configMap:
            name: {{ include "nrdot.fullname" . }}-{{ .name }}-config
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
