# TestForge-K8s v1.0 SLO and MFR Thresholds
# Reference values for EIDC v1.2 validation

# System-wide SLO thresholds
slo:
  VOL:
    ingest_volume_reduction_percent:
      target: 70.0
      blocking: true
      min_acceptable: 65.0
  
  SER:
    process_series_reduction_percent:
      target: 90.0
      blocking: true
      min_acceptable: 85.0
  
  ALR-R:
    alert_recall_percent:
      target: 98.0
      blocking: true
      min_acceptable: 95.0
  
  ALR-P:
    alert_precision_percent:
      target: 90.0
      blocking: true
      min_acceptable: 85.0
  
  TOP5:
    diagnostic_integrity_percent:
      target: 100.0
      blocking: true
      min_acceptable: 100.0
    metric_accuracy_percent:
      target: 90.0
      blocking: true
      min_acceptable: 85.0
  
  CPU:
    collector_cpu_vcores_p90:
      target: 1.0
      blocking: true
      max_acceptable: 1.2
  
  RAM:
    collector_ram_gib_p90:
      target: 1.0
      blocking: true
      max_acceptable: 1.2
    dropped_datapoints_percent:
      target: 0.01
      blocking: true
      max_acceptable: 0.05
  
  LAT:
    pipeline_latency_ms_p95:
      target: 1000
      blocking: true
      max_acceptable: 1500

# Functional MFR validation thresholds
mfr:
  SC.1:
    valid_receiver_configs:
      target: true
      blocking: true
  
  SC.1.4:
    pid_enrichment_success_rate:
      target: 95.0
      blocking: true
      min_acceptable: 90.0
    fallback_boot_id_presence:
      target: true
      blocking: true
  
  SC.3:
    schema_compliance_percent:
      target: 100.0
      blocking: true
      min_acceptable: 99.0
  
  SC.3.1:
    delta_temporality_compliance:
      target: true
      blocking: true
  
  SC.4.2:
    command_line_hashing:
      target: true
      blocking: true
    raw_command_line_absent:
      target: true
      blocking: true
  
  SC.5:
    source_priority_correct:
      target: true
      blocking: true
    no_duplicate_processes:
      target: true
      blocking: true

# Security validation thresholds (optional gates)
security:
  SEC-1:
    sbom_present:
      target: true
      blocking: false
    no_critical_cves:
      target: true
      blocking: false
  
  SEC-2:
    valid_signatures:
      target: true
      blocking: false
  
  SEC-3:
    seccomp_profile_enforced:
      target: true
      blocking: false
    minimal_capabilities:
      target: true
      blocking: false