apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nrdotpluspipelines.nrdot.newrelic.com
spec:
  group: nrdot.newrelic.com
  names:
    kind: NRDotPlusPipeline
    listKind: NRDotPlusPipelineList
    plural: nrdotpluspipelines
    singular: nrdotpluspipeline
    shortNames:
      - nrpl
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pipelineVersion:
                  type: string
                  description: "Version of the pipeline configuration schema"
                globalSettings:
                  type: object
                  properties:
                    deterministicSeedEnvVar:
                      type: string
                      description: "Environment variable name containing the deterministic seed for sampling"
                    internalLabelPolicy:
                      type: string
                      enum: ["preserve", "strip", "validate"]
                      description: "Policy for handling internal labels"
                functionBlocks:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: "Whether this function block is enabled"
                      imageTag:
                        type: string
                        description: "Override the container image tag for this function block"
                      parameters:
                        type: object
                        description: "Function block specific parameters"
                        x-kubernetes-preserve-unknown-fields: true
                        properties:
                          # RX parameters
                          endpoints:
                            type: array
                            items:
                              type: object
                              properties:
                                protocol:
                                  type: string
                                  enum: ["otlp/grpc", "otlp/http", "prometheus/remote-write"]
                                port:
                                  type: integer
                                  minimum: 1
                                  maximum: 65535
                                enabled:
                                  type: boolean

                          # Enrichment parameters
                          host:
                            type: object
                            properties:
                              enabled:
                                type: boolean
                              cacheTTL:
                                type: string
                                pattern: "^[0-9]+(m|s|h)$"
                          kubernetes:
                            type: object
                            properties:
                              enabled:
                                type: boolean
                              cacheTTL:
                                type: string
                                pattern: "^[0-9]+(m|s|h)$"

                          # Classification parameters
                          piiFields:
                            type: array
                            items:
                              type: string
                          saltSecretName:
                            type: string
                          piiSaltVersion:
                            type: integer

                          # Deduplication parameters
                          gcInterval:
                            type: string
                            pattern: "^[0-9]+(m|s|h)$"
                          storagePath:
                            type: string

                          # Filter & Sample parameters
                          rules:
                            type: array
                            items:
                              type: object
                              properties:
                                pattern:
                                  type: string
                                sampleRate:
                                  type: number
                                  minimum: 0
                                  maximum: 1

                          # Aggregation parameters
                          statefulBackendEnabled:
                            type: boolean
                          windows:
                            type: array
                            items:
                              type: object
                              properties:
                                duration:
                                  type: string
                                  pattern: "^[0-9]+(m|s|h)$"
                                operations:
                                  type: array
                                  items:
                                    type: string
                                    enum: ["sum", "count", "avg", "min", "max", "p50", "p90", "p95", "p99"]

                          # Gateway Pre parameters
                          maxRetentionHours:
                            type: integer
                            minimum: 1
                            maximum: 24
                          watermarkPercentage:
                            type: integer
                            minimum: 50
                            maximum: 95

                          # Gateway parameters
                          schemaEnforce:
                            type: boolean
                          exportEndpoint:
                            type: string

                          # DLQ parameters
                          maxSizeGB:
                            type: integer
                            minimum: 1
                          backend:
                            type: string
                            enum: ["leveldb", "kafka"]
              required: ["functionBlocks"]
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                configGenerationApplied:
                  type: integer
                fbStatus:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ready:
                        type: boolean
                      configApplied:
                        type: boolean
                      configGeneration:
                        type: integer
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Version
          type: string
          jsonPath: .spec.pipelineVersion
        - name: Config
          type: integer
          jsonPath: .status.configGenerationApplied
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}