# Lab-specific values for NRDOT+ Internal Dev-Lab
# Intended for local development and testing

global:
  registry: docker-internal.newrelic.com
  imageTag: latest
  imagePullPolicy: Always
  
  # Override observability endpoints for lab environment
  observability:
    prometheusEndpoint: http://prometheus.monitoring.svc.cluster.local:9090
    otlpEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    traceSamplingRatio: 0.5  # Higher sampling for lab environment

# Adjust resource requirements for lab environment
fb:
  rx:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  
  dp:
    persistence:
      size: 5Gi  # Smaller for lab
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
  
  gwPre:
    persistence:
      size: 10Gi  # Smaller for lab
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  
  dlq:
    persistence:
      size: 5Gi  # Smaller for lab

# Enable Kafka for lab testing
kafka:
  enabled: true

# Use a more aggressive configuration for lab testing
defaultPipeline:
  enrichment:
    host:
      cacheTTL: 5m  # More frequent updates for testing
    kubernetes:
      cacheTTL: 2m  # More frequent updates for testing
  
  deduplication:
    gcInterval: 2m  # More frequent GC for testing
  
  filterAndSample:
    rules:
      - pattern: "test\\..*"
        sampleRate: 1.0  # No sampling for test metrics in lab
      - pattern: "dev\\..*"
        sampleRate: 1.0  # No sampling for dev metrics in lab
  
  gateway:
    pre:
      maxRetentionHours: 4  # Shorter retention for lab
      watermarkPercentage: 90  # Higher watermark to test backpressure
    exportEndpoint: https://metric-api.staging.newrelic.com  # Use staging endpoint
  
  circuitBreakers:
    defaults:
      errorThresholdPercentage: 30  # Lower threshold to test circuit breaker behavior
      openStateSeconds: 15  # Shorter open state for faster recovery in testing
