# Default values for NRDOT+ Internal Dev-Lab
# This is a YAML-formatted file.

global:
  registry: docker-internal.newrelic.com
  imageTag: 2.1.2
  imagePullPolicy: IfNotPresent
  
  # Common labels
  labels:
    app.kubernetes.io/name: nrdot-internal-devlab
    app.kubernetes.io/version: "2.1.2"
    app.kubernetes.io/managed-by: helm

  # Network configuration
  network:
    internalDomain: nrdot.svc.cluster.local

  # Observability configuration
  observability:
    prometheusEndpoint: http://prometheus:9090
    otlpEndpoint: http://otel-collector:4317
    traceSamplingRatio: 0.1

  # Resources defaults (can be overridden per component)
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# ConfigController configuration
configController:
  replicas: 1
  image:
    repository: nrdot-internal-devlab/config-controller
    tag: null  # Defaults to global.imageTag
  leaderElection:
    enabled: true
    leaseDuration: 15s
    renewDeadline: 10s
    retryPeriod: 2s
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Function Block common configuration
fb:
  common:
    ports:
      metrics: 2112
      grpc: 5000
    probes:
      liveness:
        initialDelaySeconds: 10
        periodSeconds: 10
      readiness:
        initialDelaySeconds: 5
        periodSeconds: 5

  # FB-RX (Receiver)
  rx:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-rx
      tag: null  # Defaults to global.imageTag
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
    ports:
      otlpGrpc: 4317
      otlpHttp: 4318
      promRemoteWrite: 9009
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  # FB-EN-HOST (Host Enrichment)
  enHost:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-en-host
      tag: null
    resources: {}  # Use global defaults

  # FB-EN-K8S (Kubernetes Enrichment)
  enK8s:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-en-k8s
      tag: null
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
    resources: {}  # Use global defaults

  # FB-CL (Classification)
  cl:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-cl
      tag: null
    piiSalt:
      secretName: pii-salt
      secretKey: salt
    resources: {}  # Use global defaults

  # FB-DP (Deduplication)
  dp:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-dp
      tag: null
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
    persistence:
      enabled: true
      storageClass: "standard"
      size: 10Gi
      accessMode: ReadWriteOnce
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

  # FB-FS (Filter/Sample)
  fs:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-fs
      tag: null
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 8
    resources: {}  # Use global defaults

  # FB-AGG (Aggregation)
  agg:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-agg
      tag: null
    statefulBackend:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 512Mi

  # FB-GW-PRE (Gateway Pre-processing)
  gwPre:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-gw-pre
      tag: null
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
    persistence:
      enabled: true
      storageClass: "standard"
      size: 20Gi
      accessMode: ReadWriteOnce
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 512Mi

  # FB-GW (Gateway)
  gw:
    replicas: 2
    image:
      repository: nrdot-internal-devlab/fb-gw
      tag: null
    export:
      endpoint: https://metric-api.newrelic.com
      apiKeySecret:
        name: nr-api-key
        key: api-key
    resources: {}  # Use global defaults

  # FB-DLQ (Dead Letter Queue)
  dlq:
    replicas: 1
    image:
      repository: nrdot-internal-devlab/fb-dlq
      tag: null
    persistence:
      enabled: true
      storageClass: "standard"
      size: 10Gi
      accessMode: ReadWriteOnce
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

# Optional Kafka configuration for extended DLQ tests
kafka:
  enabled: false  # Set to true to deploy a single-broker Kafka instance
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 20Gi

# Default pipeline configuration
defaultPipeline:
  enabled: true
  name: default-pipeline
  rx:
    endpoints:
      - protocol: otlp/grpc
        port: 4317
      - protocol: otlp/http
        port: 4318
      - protocol: prometheus/remote-write
        port: 9009
  enrichment:
    host:
      enabled: true
      cacheTTL: 10m
    kubernetes:
      enabled: true
      cacheTTL: 5m
  classification:
    piiFields:
      - command_line
      - user_name
      - email
      - ip_address
    saltSecretName: pii-salt
  deduplication:
    enabled: true
    gcInterval: 5m
    storagePath: /data/badger
  filterAndSample:
    rules:
      - pattern: "test\\..*"
        sampleRate: 0.1
      - pattern: "dev\\..*"
        sampleRate: 0.5
  aggregation:
    statefulBackendEnabled: false
    windows:
      - duration: 60s
        operations:
          - sum
          - count
          - avg
          - p95
      - duration: 300s
        operations:
          - sum
          - count
          - avg
          - p95
  gateway:
    pre:
      maxRetentionHours: 24
      watermarkPercentage: 80
    schemaEnforce: true
    exportEndpoint: https://metric-api.newrelic.com
  deadLetterQueue:
    storagePath: /data/dlq
    maxSizeGB: 5
  circuitBreakers:
    defaults:
      errorThresholdPercentage: 50
      openStateSeconds: 30
      halfOpenRequestThreshold: 5
    overrides:
      - fbName: fb-agg
        errorThresholdPercentage: 70
        openStateSeconds: 60
