name: Check EIDC Spec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml yamllint markdownlint-cli
      
      - name: Lint YAML
        run: |
          yamllint eidc tf-k8s
      
      - name: Print changed files
        if: github.event_name == 'pull_request'
        run: |
          git diff --name-only origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | grep -v "^\\." || echo "No non-hidden files changed"
      
      - name: Validate schemas
        run: |
          python .ci/validate_schemas.py
      
      - name: Check schema-docs sync
        run: |
          python .ci/check_docs_drift.py
  
  pr-size-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check PR size
        run: |
          ADDED_LINES=$(git diff --stat origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | tail -n 1 | awk '{print $4}')
          echo "Lines changed: $ADDED_LINES"
          if [ "$ADDED_LINES" -gt 400 ]; then
            echo "::error::PR exceeds maximum size of 400 lines. Please split into smaller PRs."
            exit 1
          fi
