name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify test matrix
        run: python tools/test-matrix-builder/test_matrix_builder.py --verify
  
  lint:
    needs: [matrix-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
  
  unit-test:
    needs: [matrix-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Unit Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
      - name: Sync PRD appendices
        run: python tools/test-matrix-builder/test_matrix_builder.py
      
  build:
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Build
        run: go build -v ./...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Function Blocks
        run: ./scripts/build-all.sh