name: Coverage Drift Check

on:
  pull_request:
    paths:
      - 'eidc/**/*.yaml'
      - 'eidc/**/*.json'
      - 'tf-k8s/**/*.yaml'
      - 'tf-k8s/**/*.json'
  push:
    branches:
      - main
    paths:
      - 'eidc/**/*.yaml'
      - 'eidc/**/*.json'
      - 'tf-k8s/**/*.yaml'
      - 'tf-k8s/**/*.json'

jobs:
  check-drift:
    name: Check Documentation Drift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install pyyaml jinja2 jsonschema
      
      - name: Generate docs from schemas
        run: |
          mkdir -p .tmp/generated
          python .ci/scripts/generate_docs.py
      
      - name: Compare generated docs with committed docs
        run: |
          DIFF_OUTPUT=$(diff -r .tmp/generated/ docs/ || true)
          if [[ ! -z "$DIFF_OUTPUT" ]]; then
            echo "Documentation drift detected!"
            echo "$DIFF_OUTPUT"
            if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
              # On main branch push, create an issue
              ISSUE_TITLE="Documentation Drift Detected"
              ISSUE_BODY="The following documentation files are out of sync with their source schemas:\n\n\`\`\`\n$DIFF_OUTPUT\n\`\`\`\n\nPlease update the documentation to match the source schemas."
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues \
                -d "{\"title\":\"$ISSUE_TITLE\",\"body\":\"$ISSUE_BODY\",\"labels\":[\"documentation\",\"drift\"]}"
            else
              # On PR, fail the check
              exit 1
            fi
          else
            echo "No documentation drift detected."
          fi