name: TF-K8s Functional Tests

on:
  pull_request:
    paths:
      - 'tf-k8s/1.0/scenarios/**'
      - 'eidc/**'
  push:
    branches:
      - main
    paths:
      - 'tf-k8s/1.0/scenarios/**'
      - 'eidc/**'

jobs:
  determine-scenarios:
    name: Determine Affected Scenarios
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.get-scenarios.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - id: get-scenarios
        name: Get affected scenarios
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          fi
          
          # Extract scenario IDs from changed files
          SCENARIOS=$(echo "$CHANGED_FILES" | grep -o 'TF-[^/]*' | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "scenarios=$SCENARIOS" >> $GITHUB_OUTPUT
  
  run-tests:
    name: Run Tests
    needs: determine-scenarios
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: ${{ fromJson(needs.determine-scenarios.outputs.scenarios) }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Kind
        uses: helm/kind-action@v1.5.0
        with:
          wait: 120s
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r tf-k8s/requirements.txt
      
      - name: Run scenario
        run: |
          python tf-k8s/scripts/scenario-runner.py --scenario ${{ matrix.scenario }} --cluster kind